# 张量

张量是一种专门的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于 NumPy 的 ndarrays，但张量可以在 GPU 或其他专用硬件上运行以加速计算。

In [2]:
import torch
import numpy as np

### 1. 张量初始化

#### 直接从数据创建
可以从数据直接创建张量。数据类型会自动推断。


In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

#### 从 NumPy 数组创建

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### 从另一个张量创建

In [5]:
# 新张量会保留参数张量的属性（形状、数据类型），除非显式覆盖。

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5703, 0.6892],
        [0.9512, 0.7684]]) 



#### 使用随机值或常数值创建

shape 是张量维度的元组。在下面的函数中，它决定输出张量的维度。

In [6]:
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4271, 0.4016, 0.4530],
        [0.8603, 0.0437, 0.7411]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2. 张量属性

In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. 张量操作
100 多种张量操作，包括转置、索引、切片、数学运算、线性代数、随机采样等等，在 [这里](https://pytorch.ac.cn/docs/stable/torch.html) 有详细的介绍。

它们中的每一个都可以运行在 GPU 上（通常比 CPU 上的速度更快）。如果您使用的是 Colab，请转到“编辑”>“笔记本设置”分配 GPU。

In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [9]:
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### 3.1 标准 NumPy 式索引和切片


In [10]:
tensor = torch.ones(4,4)
tensor[:,1]=0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

连接张量 可以使用 torch.cat 在给定维度上连接张量序列。另见 torch.stack，另一个与 torch.cat 略有不同的张量连接操作。

In [11]:
t1 = torch.cat([tensor, tensor, tensor, tensor], dim=1)

# dim=1表示在列方向上连接，列会增加

### 3.2 张量乘法


In [12]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

print(f"tensor * tensor \n  {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


这计算两个张量之间的矩阵乘法。

In [13]:
# 数组的乘法是： mul，矩阵的乘法是：matmul
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

# 数组的乘法是：* 矩阵的乘法是：@
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


就地操作 具有 **_** 后缀的操作是就地操作。例如：x.copy_(y)、x.t_() 将改变 x。

In [14]:

print(tensor, "\n")
tensor.add_(5)
print(tensor)

# tensor并没有变
tensor.add(5)
print(tensor)

x = tensor.add(5)
print(x)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


就地操作可以节省一些内存，但由于会立即丢失历史记录，因此在计算导数时可能会出现问题。因此，不建议使用。

## 与 NumPy 的桥梁
CPU 上的张量和 NumPy 数组可以共享其底层内存位置，更改一个将更改另一个。

### 张量到 Numpy 数组

In [16]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


张量的变化反映在 NumPy 数组中。

In [19]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([4., 4., 4., 4., 4.])
n: [4. 4. 4. 4. 4.]


### NumPy 数组到张量

In [20]:
n = np.ones(5)

In [21]:
t = torch.from_numpy(n)

NumPy 数组的变化反映在张量中。

In [22]:
np.add(n, 1, out=n) # out=n 意味着计算结果将直接写入 n，而不是创建一个新的数组。
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
